/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum.enam;

import praktikum.lima.DBConnection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author daffa
 */
public class CRUDMahasiswa extends javax.swing.JFrame {
    
    private Statement stm;
    private ResultSet rst;
    private Connection conn;
    String sql = "";
    /**
     * Creates new form CRUDMahasiswa
     */
    public CRUDMahasiswa() {
        initComponents();
        
        conn = DBConnection.getConnection();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNIM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTTL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNomorHP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbPria = new javax.swing.JRadioButton();
        cbWanita = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        cbxProdi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Mahasiswa/i");

        jLabel2.setText("NIM");

        jLabel3.setText("Tempat, Tanggal Lahir");

        jLabel4.setText("Nomor HP");

        jLabel5.setText("Jenis Kelamin");

        buttonGroup1.add(cbPria);
        cbPria.setText("Pria");

        buttonGroup1.add(cbWanita);
        cbWanita.setText("Wanita");

        jLabel6.setText("Prodi");

        cbxProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Prodi ---", "Teknik Informatika", "Manajemen", "Bisnis Digital", "Ekonomi Syariah" }));

        jLabel7.setText("Alamat");

        taAlamat.setColumns(20);
        taAlamat.setRows(5);
        jScrollPane1.setViewportView(taAlamat);

        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "NIM", "TTL", "Nomor", "JK", "Prodi", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMahasiswa);

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 2, 36)); // NOI18N
        jLabel8.setText("Daftar Mahasiswa");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbah(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear(evt);
            }
        });

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbPria)
                                .addGap(18, 18, 18)
                                .addComponent(cbWanita))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfNIM)
                                .addComponent(tfNama)
                                .addComponent(tfTTL, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfNomorHP, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                        .addComponent(cbxProdi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(294, 294, 294))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfTTL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNomorHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbPria)
                            .addComponent(cbWanita))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbxProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tampilData() {
        DefaultTableModel kolomTabel = (DefaultTableModel) tblMahasiswa.getModel();        
        kolomTabel.setRowCount(0);
        
        try {    
            int nomor = 1;
            
            PreparedStatement pStm = conn.prepareStatement("SELECT * FROM mahasiswa");            
            rst = pStm.executeQuery();
            
            while (rst.next()) {  
                Object[] rowData = {
                    Integer.toString(nomor),
                    rst.getString("nama"),
                    rst.getString("nim"),
                    rst.getString("ttl"),
                    rst.getString("nomor_hp"),
                    rst.getString("jenis_kelamin"),
                    rst.getString("prodi"),
                    rst.getString("alamat"),
                };
                
                kolomTabel.addRow(rowData);
                
                nomor++;                
            }            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void clear() {
        tfNama.setText("");
        tfTTL.setText("");
        tfNomorHP.setText("");
        tfNIM.setText("");
        buttonGroup1.clearSelection();
        cbxProdi.setSelectedItem("--- Prodi ---");
        taAlamat.setText("");
    }
    
    private void btnUbah(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbah
        // TODO add your handling code here:
        String nim = JOptionPane.showInputDialog("Masukan NIM: ");
        
        try {
            PreparedStatement pStm = conn.prepareStatement("SELECT nim FROM mahasiswa WHERE nim = ?");
            pStm.setString(1, nim);            
            rst = pStm.executeQuery();
            
            if(rst.next()) {
                UpdateMahasiswa formUpdate = new UpdateMahasiswa(nim);
                formUpdate.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");              
            }                                                   
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }                        
    }//GEN-LAST:event_btnUbah

    private void btnHapus(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus
        // TODO add your handling code here:
        String nim = JOptionPane.showInputDialog("Masukan NIM: ");                
        
        try {
            PreparedStatement pStm = conn.prepareStatement("DELETE FROM mahasiswa WHERE nim = ?");
            pStm.setString(1, nim);            
            int isSuccess = pStm.executeUpdate();
            
            if(isSuccess > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");              
                tampilData();
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");              
            }                                                   
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }                     
    }//GEN-LAST:event_btnHapus

    private void btnSubmit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit
        // TODO add your handling code here:       
        String nama, jenis_kelamin, alamat, ttl, no_hp, nim;       
        
        nama = tfNama.getText();
        alamat = taAlamat.getText();
        ttl = tfTTL.getText();
        Object prodi = cbxProdi. getSelectedItem();
        no_hp = tfNomorHP.getText();
        nim = tfNIM.getText();
        
        if(cbPria.isSelected()) {
            jenis_kelamin = "pria";
        } else {
            jenis_kelamin = "wanita";
        }
        
        try {           
            PreparedStatement pStm = conn.prepareStatement("INSERT INTO mahasiswa VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
            pStm.setString(1, null);
            pStm.setString(2, nama);            
            pStm.setString(3, nim);
            pStm.setString(4, ttl);
            pStm.setString(5, no_hp);            
            pStm.setString(6, jenis_kelamin);
            pStm.setString(7, String.valueOf(cbxProdi.getSelectedItem()));
            pStm.setString(8, alamat);
            pStm.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            
            tampilData();
            clear();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnSubmit

    private void btnClear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClear

    private void btnExit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit
        // TODO add your handling code here:
        int jawab = JOptionPane.showConfirmDialog(this, "Ingin keluar?", "Exit", JOptionPane.NO_OPTION, JOptionPane.YES_OPTION);
        
        if(jawab == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExit

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cbPria;
    private javax.swing.JRadioButton cbWanita;
    private javax.swing.JComboBox<String> cbxProdi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField tfNIM;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNomorHP;
    private javax.swing.JTextField tfTTL;
    // End of variables declaration//GEN-END:variables
}
